export const filterOptions = [
  { label: "Alcohol", value: "bars" },
  { label: "American", value: "tradamerican" },
  { label: "Boba", value: "bubbletea" },
  { label: "Breakfast", value: "breakfast_brunch" },
  { label: "Chinese", value: "chinese" },
  { label: "Desserts", value: "desserts" },
  { label: "Food Trucks", value: "foodtrucks" },
  { label: "Fast Food", value: "hotdogs" },
  { label: "Indian", value: "indpak" },
  { label: "Japanese", value: "japanese" },
  { label: "Mexican", value: "mexican" },
  { label: "Thai", value: "thai" },
  { label: "Halal", value: "halal" },
  { label: "Vegan", value: "vegan" },
  { label: "Vegetarian", value: "vegetarian" },
  { label: "Kosher", value: "kosher" },
];
